import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Steves Franc T. | Space Portfolio",
  description: "Développeur web full-stack spécialisé en API, fintech et infrastructures scalables. Découvrez mes projets, collaborations et compétences techniques.",
  icons: {
    icon: "/wonder-app/svg/favicon.svg",
   },
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Steves Franc T.",
    url: "https://github.com/stevesfranct",
  },
} as const;